
import javax.swing.JFrame;
import java.awt.Desktop;
import java.net.URI;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
//import java.awt.Color;
//import java.awt.*;

/**
 *
 * @author mhmir
 */
public class Login_Page extends javax.swing.JFrame {

    PreparedStatement p;
    ResultSet r;
    
    /**
     * Creates new form Login_Page
     */
    public Login_Page() {
        initComponents();
        this.setLocationRelativeTo(null);//opens tab in center of the screen

//        jTextFieldUserName.setBackground(new java.awt.Color(0,0,0,64));//Makes the field transparent
//        jPasswordField1.setBackground(new java.awt.Color(0,0,0,64));//Makes the field transparent
//        jComboBoxLoginAs.setBackground(new java.awt.Color(0,0,0,0));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabelClose = new javax.swing.JLabel();
        jLabelMinimize = new javax.swing.JLabel();
        jTextFieldUserName = new javax.swing.JTextField();
        jPasswordField1 = new javax.swing.JPasswordField();
        jButtonLogin = new javax.swing.JButton();
        jLabelRegister = new javax.swing.JLabel();
        jComboBoxLoginAs = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabe4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabelFacebook = new javax.swing.JLabel();
        AdminFacebook = new javax.swing.JLabel();
        AdminFacebook1 = new javax.swing.JLabel();
        AdminFacebook2 = new javax.swing.JLabel();
        AdminFacebook3 = new javax.swing.JLabel();
        AdminFacebook4 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabelLoginBackgroundImage = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setUndecorated(true);
        setResizable(false);
        setType(java.awt.Window.Type.POPUP);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel11.setFont(new java.awt.Font("Modern No. 20", 3, 48)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(204, 255, 255));
        jLabel11.setText("SKYLINE AIRLINES");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 40, 590, 60));

        jLabel10.setFont(new java.awt.Font("Modern No. 20", 3, 36)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(204, 255, 255));
        jLabel10.setText("FLY SAFE");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 290, 220, 60));

        jLabelClose.setBackground(new java.awt.Color(255, 0, 51));
        jLabelClose.setFont(new java.awt.Font("Vrinda", 0, 30)); // NOI18N
        jLabelClose.setForeground(new java.awt.Color(204, 255, 255));
        jLabelClose.setText("X");
        jLabelClose.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelClose.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelCloseMouseClicked(evt);
            }
        });
        jPanel1.add(jLabelClose, new org.netbeans.lib.awtextra.AbsoluteConstraints(1570, 10, -1, -1));

        jLabelMinimize.setBackground(new java.awt.Color(255, 0, 51));
        jLabelMinimize.setFont(new java.awt.Font("Vrinda", 0, 36)); // NOI18N
        jLabelMinimize.setForeground(new java.awt.Color(204, 255, 255));
        jLabelMinimize.setText("-");
        jLabelMinimize.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelMinimize.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelMinimizeMouseClicked(evt);
            }
        });
        jPanel1.add(jLabelMinimize, new org.netbeans.lib.awtextra.AbsoluteConstraints(1530, 10, -1, 50));

        jTextFieldUserName.setBackground(new java.awt.Color(204, 255, 255));
        jTextFieldUserName.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jTextFieldUserName.setForeground(new java.awt.Color(0, 153, 153));
        jTextFieldUserName.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jTextFieldUserName.setSelectionColor(java.awt.Color.black);
        jTextFieldUserName.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextFieldUserNameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextFieldUserNameFocusLost(evt);
            }
        });
        jTextFieldUserName.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextFieldUserNameMouseClicked(evt);
            }
        });
        jTextFieldUserName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldUserNameActionPerformed(evt);
            }
        });
        jPanel1.add(jTextFieldUserName, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 320, 560, 80));

        jPasswordField1.setBackground(new java.awt.Color(204, 255, 255));
        jPasswordField1.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jPasswordField1.setForeground(new java.awt.Color(0, 153, 153));
        jPasswordField1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jPasswordField1.setHighlighter(null);
        jPasswordField1.setSelectionColor(java.awt.Color.black);
        jPasswordField1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jPasswordField1FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jPasswordField1FocusLost(evt);
            }
        });
        jPasswordField1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPasswordField1MouseClicked(evt);
            }
        });
        jPanel1.add(jPasswordField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 480, 560, 80));

        jButtonLogin.setBackground(new java.awt.Color(0, 204, 255));
        jButtonLogin.setFont(new java.awt.Font("Calibri", 1, 36)); // NOI18N
        jButtonLogin.setForeground(new java.awt.Color(255, 255, 255));
        jButtonLogin.setText("LOGIN");
        jButtonLogin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonLogin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonLoginMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButtonLoginMouseEntered(evt);
            }
        });
        jButtonLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLoginActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 670, 560, 80));

        jLabelRegister.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabelRegister.setForeground(java.awt.Color.cyan);
        jLabelRegister.setText("Signup");
        jLabelRegister.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelRegister.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelRegisterMouseClicked(evt);
            }
        });
        jPanel1.add(jLabelRegister, new org.netbeans.lib.awtextra.AbsoluteConstraints(1056, 820, 90, 50));

        jComboBoxLoginAs.setBackground(new java.awt.Color(204, 255, 255));
        jComboBoxLoginAs.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jComboBoxLoginAs.setForeground(new java.awt.Color(204, 255, 255));
        jComboBoxLoginAs.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Passenger", "Admin" }));
        jComboBoxLoginAs.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 102, 102), 1, true));
        jComboBoxLoginAs.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jComboBoxLoginAs.setEditor(null);
        jComboBoxLoginAs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxLoginAsActionPerformed(evt);
            }
        });
        jPanel1.add(jComboBoxLoginAs, new org.netbeans.lib.awtextra.AbsoluteConstraints(1120, 162, 370, 80));

        jLabel1.setFont(new java.awt.Font("Tahoma", 2, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Forgot your password ?");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1230, 805, 270, 80));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(204, 255, 255));
        jLabel2.setText("Login as");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 160, 190, 80));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(204, 255, 255));
        jLabel3.setText("User ID/Email");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 250, 560, 80));

        jLabe4.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabe4.setForeground(new java.awt.Color(204, 255, 255));
        jLabe4.setText("Password");
        jPanel1.add(jLabe4, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 410, 560, 80));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Newuser ?");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 805, 120, 80));

        jLabelFacebook.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/facebook-6-64.png"))); // NOI18N
        jPanel1.add(jLabelFacebook, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 860, 70, 90));

        AdminFacebook.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        AdminFacebook.setForeground(java.awt.Color.white);
        AdminFacebook.setText("Mahady Hasan");
        AdminFacebook.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        AdminFacebook.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AdminFacebookMouseClicked(evt);
            }
        });
        jPanel1.add(AdminFacebook, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 870, 130, -1));

        AdminFacebook1.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        AdminFacebook1.setForeground(java.awt.Color.white);
        AdminFacebook1.setText("Anika Jahan");
        AdminFacebook1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        AdminFacebook1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AdminFacebook1MouseClicked(evt);
            }
        });
        jPanel1.add(AdminFacebook1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 890, 120, -1));

        AdminFacebook2.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        AdminFacebook2.setForeground(java.awt.Color.white);
        AdminFacebook2.setText("Sayem Imran");
        AdminFacebook2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        AdminFacebook2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AdminFacebook2MouseClicked(evt);
            }
        });
        jPanel1.add(AdminFacebook2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 910, 120, -1));

        AdminFacebook3.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        AdminFacebook3.setForeground(java.awt.Color.white);
        AdminFacebook3.setText("Partho Banik");
        AdminFacebook3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        AdminFacebook3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AdminFacebook3MouseClicked(evt);
            }
        });
        jPanel1.add(AdminFacebook3, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 890, 110, -1));

        AdminFacebook4.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        AdminFacebook4.setForeground(java.awt.Color.white);
        AdminFacebook4.setText("Bonna Sarker");
        AdminFacebook4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        AdminFacebook4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AdminFacebook4MouseClicked(evt);
            }
        });
        jPanel1.add(AdminFacebook4, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 910, 110, -1));

        jLabel12.setFont(new java.awt.Font("Modern No. 20", 3, 36)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(204, 255, 255));
        jLabel12.setText("FLY HIGH");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 260, 230, 60));

        jLabelLoginBackgroundImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/airplane-1644819248277-908 (1).jpg"))); // NOI18N
        jPanel1.add(jLabelLoginBackgroundImage, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabelCloseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelCloseMouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jLabelCloseMouseClicked

    private void jLabelMinimizeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelMinimizeMouseClicked
        // TODO add your handling code here:
        this.setState(JFrame.ICONIFIED);
    }//GEN-LAST:event_jLabelMinimizeMouseClicked

    private void jButtonLoginMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonLoginMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonLoginMouseClicked

    private void jButtonLoginMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonLoginMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonLoginMouseEntered

    private void jLabelRegisterMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelRegisterMouseClicked
        // TODO add your handling code here:
        Registration_Page rgp = new Registration_Page();
        rgp.setVisible(true);
//        rgp.pack();
//        rgp.setLocationRelativeTo(null);
        rgp.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_jLabelRegisterMouseClicked

    private void jTextFieldUserNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldUserNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldUserNameActionPerformed

    private void jComboBoxLoginAsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxLoginAsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxLoginAsActionPerformed

    private void jButtonLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLoginActionPerformed
        
        try{
            
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/airlinesmanagementsystem","root","");
            String sql ="SELECT * FROM registration WHERE  email=? and password=? and role=?";
            p=con.prepareStatement(sql);
            p.setString(1,jTextFieldUserName.getText().trim().toLowerCase() );
            p.setString(2,jPasswordField1.getText());
            String selectvalue=jComboBoxLoginAs.getSelectedItem().toString();
              p.setString(3,selectvalue);
            r=p.executeQuery();
            
            if("Passenger".equals(selectvalue))
            {
//                if((jTextFieldUserName.getText().isEmpty())|| (jTextFieldUserName.getText()=="abcd@gmai.com"))
//            {
//                Missing.setText("Email missing");
//            }
                if(r.next())
                {
                 this.setVisible(false);
                 new PassengerPanel().setVisible(true);
                }
                else
                {
                    JOptionPane.showMessageDialog(this," User name or Password or Role Incorrect" );
                    
                }
            }
            else
            {
                if(r.next())
                {
                    this.setVisible(false);
                    new AdminPanel().setVisible(true);  
                }
                else
                {
                    JOptionPane.showMessageDialog(this," User name or Password or Role Incorrect" );
                }
            }
        }
        catch(Exception e)
        {
        }
    }//GEN-LAST:event_jButtonLoginActionPerformed

    private void jTextFieldUserNameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldUserNameFocusLost
        // TODO add your handling code here:
        String uservalue = jTextFieldUserName.getText();
        if(uservalue.equals("abcd@gmai.com") || uservalue.equals("") )
        { 
            jTextFieldUserName.setText("abcd@gmai.com");
            
        }
    }//GEN-LAST:event_jTextFieldUserNameFocusLost

    private void jTextFieldUserNameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldUserNameFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldUserNameFocusGained

    private void jTextFieldUserNameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextFieldUserNameMouseClicked
        // TODO add your handling code here:
        String uservalue = jTextFieldUserName.getText();
        if(uservalue.equals("abcd@gmai.com") || uservalue.equals("") )
        { 
            jTextFieldUserName.setText("");
          
        }
    }//GEN-LAST:event_jTextFieldUserNameMouseClicked

    private void jPasswordField1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jPasswordField1FocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_jPasswordField1FocusGained

    private void jPasswordField1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jPasswordField1FocusLost
        // TODO add your handling code here:
//                String uservalue = jPasswordField1.getText();
//        if(uservalue.equals("Password") || uservalue.equals("") )
//        { 
//            jPasswordField1.setText("Password");
//        }
    }//GEN-LAST:event_jPasswordField1FocusLost

    private void jPasswordField1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPasswordField1MouseClicked
        // TODO add your handling code here:
//                String uservalue = jPasswordField1.getText();
//        if(uservalue.equals("Password") || uservalue.equals("") )
//        { 
//            jPasswordField1.setText("");
//        }
    }//GEN-LAST:event_jPasswordField1MouseClicked

    private void AdminFacebookMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AdminFacebookMouseClicked
        // TODO add your handling code here:
        Desktop browser=Desktop.getDesktop();
        try{
            browser.browse(new URI("https://www.facebook.com/mh.miraz30/"));
        }catch(Exception e){}
    }//GEN-LAST:event_AdminFacebookMouseClicked

    private void AdminFacebook1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AdminFacebook1MouseClicked
        // TODO add your handling code here:
        Desktop browser=Desktop.getDesktop();
        try{
            browser.browse(new URI("https://www.facebook.com/rimasanika44"));
        }catch(Exception e){}
    }//GEN-LAST:event_AdminFacebook1MouseClicked

    private void AdminFacebook2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AdminFacebook2MouseClicked
        // TODO add your handling code here:
        Desktop browser=Desktop.getDesktop();
        try{
            browser.browse(new URI("https://www.facebook.com/sayem.somrat"));
        }catch(Exception e){}
    }//GEN-LAST:event_AdminFacebook2MouseClicked

    private void AdminFacebook3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AdminFacebook3MouseClicked
        // TODO add your handling code here:
        Desktop browser=Desktop.getDesktop();
        try{
            browser.browse(new URI("https://www.facebook.com/Parthomerchant"));
        }catch(Exception e){}
    }//GEN-LAST:event_AdminFacebook3MouseClicked

    private void AdminFacebook4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AdminFacebook4MouseClicked
        // TODO add your handling code here:
        Desktop browser=Desktop.getDesktop();
        try{
            browser.browse(new URI("https://www.facebook.com/debangi.debi"));
        }catch(Exception e){}
    }//GEN-LAST:event_AdminFacebook4MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login_Page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login_Page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login_Page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login_Page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login_Page().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AdminFacebook;
    private javax.swing.JLabel AdminFacebook1;
    private javax.swing.JLabel AdminFacebook2;
    private javax.swing.JLabel AdminFacebook3;
    private javax.swing.JLabel AdminFacebook4;
    private javax.swing.JButton jButtonLogin;
    private javax.swing.JComboBox<String> jComboBoxLoginAs;
    private javax.swing.JLabel jLabe4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabelClose;
    private javax.swing.JLabel jLabelFacebook;
    private javax.swing.JLabel jLabelLoginBackgroundImage;
    private javax.swing.JLabel jLabelMinimize;
    private javax.swing.JLabel jLabelRegister;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JTextField jTextFieldUserName;
    // End of variables declaration//GEN-END:variables
}
