
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author mhmir
 */
public class SplashPanel extends javax.swing.JFrame {

    /**
     * Creates new form SplashPanel
     */
    public SplashPanel() {
        initComponents();
        //jProgressBar1.setBackground(new java.awt.Color(0,0,0,0));
        
        this.setLocationRelativeTo(null);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Intro = new javax.swing.JLabel();
        Intro1 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jProgressBar1 = new javax.swing.JProgressBar();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1608, 993));
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(1608, 993));
        setType(java.awt.Window.Type.POPUP);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Intro.setBackground(new java.awt.Color(0, 0, 0));
        Intro.setFont(new java.awt.Font("Berlin Sans FB", 2, 18)); // NOI18N
        Intro.setForeground(new java.awt.Color(255, 255, 255));
        Intro.setText("This Application is being Developed");
        getContentPane().add(Intro, new org.netbeans.lib.awtextra.AbsoluteConstraints(1210, 790, 300, 50));

        Intro1.setBackground(new java.awt.Color(0, 0, 0));
        Intro1.setFont(new java.awt.Font("Berlin Sans FB", 2, 18)); // NOI18N
        Intro1.setForeground(new java.awt.Color(255, 255, 255));
        Intro1.setText("& Maintained by Team ETERNALS");
        getContentPane().add(Intro1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1240, 820, 270, 50));

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(1480, 880, 80, 70));

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 900, 470, 70));

        jProgressBar1.setBorderPainted(false);
        getContentPane().add(jProgressBar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 960, 1610, 20));

        jLabel2.setFont(new java.awt.Font("Modern No. 20", 3, 55)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("WELCOME");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1040, 150, 350, 90));

        jLabel3.setFont(new java.awt.Font("Modern No. 20", 3, 55)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("TO");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1140, 210, 90, 90));

        jLabel4.setFont(new java.awt.Font("Modern No. 20", 3, 55)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("SKYLINE AIRLINES");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 270, 600, 90));

        jLabel5.setFont(new java.awt.Font("Modern No. 20", 3, 30)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("FLY HIGH");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 190, 300, 90));

        jLabel6.setFont(new java.awt.Font("Modern No. 20", 3, 30)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("FLY SAFE");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 220, 300, 90));

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Splash (1).jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SplashPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SplashPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SplashPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SplashPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
         SplashPanel splash = new SplashPanel();
         splash.setVisible(true);
         
         try
         {
             for(int i=0; i<=100;i++)
             {
                 Thread.sleep(50);
                 splash.jLabel7.setText(i+"%"); 
                 
                 if(i == 0)
                 {
                     splash.jLabel8.setText("Loading....");
                 }
                 if(i == 10)
                 {
                     splash.jLabel8.setText("Turning On Modules....");
                 }
                 if(i == 30)
                 {
                     splash.jLabel8.setText("Loading Modules....");
                 }
                 if(i == 50)
                 {
                     splash.jLabel8.setText("Connecting To Database....");
                 }
                 if(i == 70)
                 {
                     splash.jLabel8.setText("Connection Successful....");
                 }
                 if(i == 85)
                 {
                     splash.jLabel8.setText("Launching Application....");
                 }
                 
                 splash.jProgressBar1.setValue(i);

             }
         }
         catch(Exception e)
         {
             System.out.println(e.getMessage());   
         }
         new Login_Page().setVisible(true);
         splash.dispose();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Intro;
    private javax.swing.JLabel Intro1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    public static javax.swing.JProgressBar jProgressBar1;
    // End of variables declaration//GEN-END:variables
}
